version: '3'
networks:
  testNetwork:
    driver: bridge
services:  
  EMS_DB:
    image: bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_USER=admin
      - POSTGRESQL_DATABASE=EMS_DB
  pgAdmin:
    image: dpage/pgadmin4
    depends_on:
      - EMS_DB
    restart: always
    ports:
      - '5555:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - testNetwork
